### PR TITLE
Add support for tooltips

### PR DESCRIPTION
**Pull request by notEvil**
see https://github.com/jrfonseca/xdot.py/issues/71

might need some polishing (e.g. code style, max. size of tooltip window)

### CODE REVIEW

**Comment by jrfonseca** [comment]
Here too, the use of `isinstance` is not ideal.  One should instead add the suitable method to Action to achieve the desired polymorphism.  That said, I've commit this as is for now.

**Comment by jrfonseca** [comment]
Thanks

**Comment by notEvil** [comment]
> Here too, the use of `isinstance` is not ideal. One should instead add the suitable method to Action to achieve the desired polymorphism. That said, I've commit this as is for now.

I don't understand the last sentence, sry. Do you want me to add `get_tooltip` to `Jump` and create a common base class for `Jump` and `Url` with default implementation?

**Comment by jrfonseca** [comment]
What I meant is, instead of
```python
               if isinstance(item, Jump) and item.item.tooltip is not None:
                   NullAction._tooltip_label.set_markup(item.item.tooltip.decode())
                   NullAction._tooltip_window.resize(
                     NullAction._tooltip_label.get_preferred_width().natural_width,
                     NullAction._tooltip_label.get_preferred_height().natural_height
                   )
                   NullAction._tooltip_window.show()
               else:
                   NullAction._tooltip_window.hide()
                   NullAction._tooltip_label.set_markup("")
               NullAction._tooltip_item = item
```

perhaps we could fold this code into a Jump method?  Also putting _tooltip_* state into NullAction class itself as opposed of instances doesn't look right (they will cause troubles if an app uses xdot package to draw multiple graphic widtgets.

But yes, I've merged this as is.  Because these are nice improvements, I'd need to spend more time than I have now to figure the right course of action, and we can always refactor the code later.

**Pull request closed without merging**
