### PR TITLE
Handle multiple search results

### PR DESCRIPTION
**Pull request by KrilleGH**
- Always pan to the first result
- Show the number of results
- Provide a button to pan to the next result

### CODE REVIEW

**Comment by jrfonseca** [comment]
There's something weird with the `FindStatus` widget.

When I search `slash` in

    digraph G {
    quote
    newline
    tab
    slash
    slashes
    }

It appears as a empty combo box...

**Comment by KrilleGH** [comment]
I don't see anything strange with your graph, see the screenshot.
xdot

I use PyGTK 2.24.0 and GTK 2.24.22, do you have different versions? Maybe the issue is with them.

**Comment by jrfonseca** [comment]
It looks like, when the window is too narrow for the "xxx nodes found" label, it degenerates in something quite confusing:

search

And the worst is that I see this with the default window size.

**Comment by KrilleGH** [comment]
This seems to be an issue with the widget itself or with its usage, I don't know how to fix that.

**Comment by jrfonseca** [comment]
I've finally rebased and pushed this.  Thanks.

**Pull request closed without merging**
